version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA:  /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "80:80"
    networks:
      - postgres
    restart: unless-stopped
  server:
    build: server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    networks:
      - postgres
    volumes:
      - ./server:/app
    depends_on:
      - postgres


  client:
    build: client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    networks:
      - postgres
    volumes:
      - ./client:/app

networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:



